### ISSUE TITLE
Could be a typo

### ISSUE THREAD

**Issue by KayDee** [DeborahK/Angular-GettingStarted#100]
https://github.com/DeborahK/Angular-GettingStarted/blob/99ccf5bde56b257c118a99de490f68e58c2cd65a/APM-Final/src/app/products/product-list.component.ts#L23

```_listFilter``` is the name of the property but you use ```listFilter``` in the conditional operator. Is it  intentional like something i don't know that typescript does ?

(A recap) ```listFilter``` is the name of getter and setter

**Comment by DeborahK** [comment]
No, it is not a typo. The `_listFilter` is a backing field and should not be used anywhere in the code but within the getter and setter.

There are two ways to define a property in TypeScript:

1) By declaring it: 
`listFilter: string;`

2) By defining a getter and setter:

```
  get listFilter(): string {
    
  }
  set listFilter(value: string) {

  }
```

In both cases, we have a **property** named `listFilter` that we can access via `this.listFilter` in the code or bind to in the Html.

We use the getter and setter approach when we need to execute code when getting or setting the property.

In the case of using the getter and setter, we need a mechanism for retaining the value. So we define *another* variable called a "backing field". By convention this is the name of the associated property prefixed with an underscore. So in this case: `_listFilter`.

In the getter, we return the value of our backing field. In the setter, we set the value of the backing field:

'''
  private _listFilter = '';
  get listFilter(): string {
    return this._listFilter;
  }
  set listFilter(value: string) {
    this._listFilter = value;
  }
```

Make sense?

You can read more about getters and setters in TypeScript here: https://www.typescriptlang.org/docs/handbook/classes.html under the heading: Accessors.

**Comment by KayDee** [comment]
Ok, so let me repeat and confirm
```listFilter``` is the name of the getter, setter and a property.
```listFilter``` (property) is only available inside the getter and setter. To make it available outside, you used the ```_listFilter```.
Am i  right or wrong ?

**Comment by DeborahK** [comment]
Not quite.

`listFilter` is the name of the **property**.

A property is defined with EITHER a property declaration OR a getter/setter. Regardless of which way you *define* the property, it acts the same.

A property is accessible in the code using `this.listFilter` and in the template using binding to `listFilter`.

So using your text:
`listFilter` is the name of the property, declared as a getter/setter.
`_listFilter` (the backing field) *should* only be used inside the getter and setter. It's sole purpose is to hold the value of the property.
`listFilter` (the property) is available anywhere in the code or in the template.

Does that help?

You can think of a getter and setter as just an expanded version of a property declaration, nothing more nothing less. The resulting property behaves the same ... EXCEPT that it has no variable to use to store the actual property value. Hence the reason it needs the backing field (`_listFilter`) to hold its value.

**Comment by KayDee** [comment]
Now got it. One more question: Why were the getter and setter used here ?

**Comment by DeborahK** [comment]
We use the getter and setter approach when we need to execute code when getting or setting the property. 

In our sample application, we need to refilter the list of products each time the user modifies the list filter property. Since the `listFilter` is bound to the input box, it will automatically call the setter each time the user updates the input value. That is then where we add the code to filter our list.

Make sense?

**Comment by KayDee** [comment]
Yeah, totally. I'm clear now.
Thanks for explaining.
