### ISSUE TITLE
Unable to run ACM-start

### ISSUE THREAD

**Issue by niraj114** [DeborahK/Angular-GettingStarted#109]
Hi Madam,

I am getting below erroe while running project

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Niraj.kumar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle apm@0.0.0~prestart: apm@0.0.0
6 info lifecycle apm@0.0.0~start: apm@0.0.0
7 verbose lifecycle apm@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle apm@0.0.0~start: PATH: C:\Users\Niraj.kumar\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Mind Game\Angular 2\routing\routingdemo\demos\Angular-Routing\APM-Start\node_modules\.bin;C:\oraclexe\app\oracle\product\11.2.0\server\bin;;C:\Program Files (x86)\RSA SecurID Token Common;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\CloudFoundry;C:\Program Files\SourceGear\Common\DiffMerge\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\Java\jdk1.8.0_45\bin;.;C:\Users\Niraj.kumar\AppData\Local\Microsoft\WindowsApps;C:\Users\Niraj.kumar\Downloads\apache-maven-3.3.9-bin\apache-maven-3.3.9/bin;C:\Program Files\Java\jdk1.8.0_45/bin;C:\Program Files\MongoDB\Server\3.4\bin;C:\Users\Niraj.kumar\Downloads\software\apache-cassandra-2.0.5/bin;C:\Users\Niraj.kumar\Downloads\software\apache-tomcat-8.0.32/bin;C:\Python27;C:\Users\Niraj.kumar\AppData\Roaming\npm
9 verbose lifecycle apm@0.0.0~start: CWD: D:\Mind Game\Angular 2\routing\routingdemo\demos\Angular-Routing\APM-Start
10 silly lifecycle apm@0.0.0~start: Args: [ '/d /s /c', 'ng serve -o' ]
11 silly lifecycle apm@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle apm@0.0.0~start: Failed to exec start script
13 verbose stack Error: apm@0.0.0 start: `ng serve -o`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Niraj.kumar\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Niraj.kumar\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid apm@0.0.0
15 verbose cwd D:\Mind Game\Angular 2\routing\routingdemo\demos\Angular-Routing\APM-Start
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Niraj.kumar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.6.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error apm@0.0.0 start: `ng serve -o`
22 error Exit status 1
23 error Failed at the apm@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by DeborahK** [comment]
Did the `npm install` run without error?

**Comment by DeborahK** [comment]
Since I have not heard anything back from you, I'll assume you resolved your issue.
