### ISSUE TITLE
Does not work with Nodejs 12+

### ISSUE THREAD

**Issue by djechelon** [DeborahK/Angular-GettingStarted#113]
Hi, I understand this tutorial is quite old-dated.
But having the latest chocolatey version of Node (12.3.1 today) the APM-Start sample does not work.

I tried to upgrade all dependencies in package.json to the reasonable with the help of Intellij but `npm install` insists on _building_ node-sass 4.9.3, which 1) does not support Node 12, and 2) there exists a newer version of node-sass compatible with Node 12.

```
"dependencies": {
    "@angular/animations": "~7.2.15",
    "@angular/common": "~7.2.15",
    "@angular/compiler": "~7.2.15",
    "@angular/core": "^7.2.15",
    "@angular/forms": "~7.2.15",
    "@angular/http": "~7.2.15",
    "@angular/platform-browser": "~7.2.15",
    "@angular/platform-browser-dynamic": "~7.2.15",
    "@angular/router": "~7.2.15",
    "core-js": "^3.1.2",
    "node-sass": "^4.12.0",
    "rxjs": "~6.5.2",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.3",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1"
  }
```

Is it possible to update the project in order to bootstrap it? Package.json is currently the only file I have updated.

Thanks

**Comment by DeborahK** [comment]
This tutorial was updated to Angular 7 a few months ago. Angular 8 just came out *yesterday*, so its not "quite outdated"

What exactly is the issue you are having? (Before intelliJ changes)

Have you tried a different editor such as vscode? 

I'm about to get on a 7 hour train with unknown wifi and then travelling for several more days. I'll look into your issue further when i return to my office.

**Comment by DeborahK** [comment]
Also, it looks like from this: https://github.com/angular/angular-cli/issues/14357

That node 12 just came out last month and the Angular cli did not initially support it.

**Comment by djechelon** [comment]
Thanks, I will try to reinstall Node LTS which has a dedicated `choco` package capped at version 10. Then reset the branch and restart tutorial.

I will update the ticket accordingly
