### ISSUE TITLE
Filter does not show my items right away

### ISSUE THREAD

**Issue by yabbou** [DeborahK/Angular-GettingStarted#117]
Only once i edit the filter input text field (make the text field dirty) are the items displayed.

**Comment by DeborahK** [comment]
Can you provide more information? Which code are you using (APM-Start? APM-Final?). Have you made any changes?

**Comment by yabbou** [comment]
APM-Final, with some changes. 

[//rug-list.component.html
](https://github.com/yabbou/candidate-test/blob/master/front-end/src/app/rugs/rug-list/rug-list.component.html)
`<div class='card-body'>`
       `        <div class='row'>`
            `            <div class='col-md-2'>Filter by:</div>`
           `           <div class='col-md-4'>`
               `               <input type='text' [(ngModel)]='filter' />`
            `            </div>`
      `       </div>`
     `     <div class='row' *ngIf='filter'>`
           `           <div class='col-md-6'>`
          `          <h4>Filtered by: {{filter}}</h4>`
       `     </div>`
     `   </div>`
  `  </div>`

**Comment by yabbou** [comment]
In my **component.ts class**, in my _ngOnInit()_, i was still subscribing to "this.rugs" instead of "this.filteredRugs". It had not been until the _constructor_ was called that "this.filteredRugs = this.rugs;"

//old ngOnInit():
`...
this.rugService.getRugs().subscribe(
            (rugs: Rug[]) => { this.rugs = rugs; }
        );
...
`


//updated ngOnInit():
`...
this.rugService.getRugs().subscribe(
            (rugs: Rug[]) => { this.filteredRugs = rugs; }
        );
...
`

**Comment by yabbou** [comment]
Thank you very much, Deborah, for your thorough tutorials! They have been very clear and very helpful in guiding me to building my first MEAN CRUD app. :)

**Comment by DeborahK** [comment]
Great to hear you resolved the issue! Thank you for the kind words.
