### ISSUE TITLE
Why I getting this error when im trying to create a new angular project 

### ISSUE THREAD

**Issue by amiihn** [DeborahK/Angular-GettingStarted#118]
Angularjs 6: “'git' is not recognized as an internal or external command, operable program or batch file.” #4
![image](https://user-images.githubusercontent.com/51708177/60731994-301ac300-9f49-11e9-9a15-807e9acdd362.png)

**Comment by DanielRunningen** [comment]
Do you have git installed on your computer?

If you're on windows, you can install it from [here](https://git-scm.com/download/win) **(Warning: will auto download once you click!)**
If you're on any Unix-based system (MacOS, Linux, Debian, etc.) you can install git from your CLI package manager.

**Comment by amiihn** [comment]
yes i ve installed it but still facing the same error i dunno what to command i should write!

**Comment by DanielRunningen** [comment]
What command did you type that lead to this output?

What do you get if you enter `git --help`?

**Comment by amiihn** [comment]
i was about to create a new angular project, since i had another project says can't use the same folder then i changed the folder name but still have the same issue...
so all i need is to create a new angular project as im just a beginner!

**Comment by DeborahK** [comment]
It looks like the project installed properly. What happens if you just use `npm start` at this point?

**Comment by amiihn** [comment]
wow ma'am!! im really happyfor your comment!! the project i have is from your tutorial Getting Started with Angular then i wanted to create my own first hello world app so i can learn more features but this error happened.

**Comment by DeborahK** [comment]
Have you resolved this issue? Can I close it?
