### ISSUE TITLE
May want to run "npm audit fix"

### ISSUE THREAD

**Issue by coreypnorris** [DeborahK/Angular-GettingStarted#123]
![6](https://user-images.githubusercontent.com/3118697/66173512-5e21a900-e605-11e9-95f1-c1f238ea1db6.JPG)

**Comment by DeborahK** [comment]
I deleted the package-lock.json files in both folders to (hopefully) prevent this issue.

I now get this:

![image](https://user-images.githubusercontent.com/7987365/66349334-7b0ff200-e90d-11e9-9375-c0ed05a55e24.png)

**Comment by coreypnorris** [comment]
Thanks. Great work on the course BTW, I'm enjoying working through it.
