### ISSUE TITLE
Cannot run APM-Start

### ISSUE THREAD

**Issue by fwitkowski** [DeborahK/Angular-GettingStarted#130]
When trying to run the applicaiton
npm start or ng serve
I get this error:
An unhandled exception occurred: Job name "..getProjectMetadata" does not exist.

**Comment by fwitkowski** [comment]
Updated Angular (from 8 to 9) globally, angular cli and typescript. This fixed that issue.

**Comment by DeborahK** [comment]
Great that you resolved your issue.

You shouldn't have *needed* to update to Angular v9. The code should work fine with Angular v8.

Just be sure you don't run any recommended `fix` as that updates some of the files making mismatches. If you delete the folder, re download or upzip it, and run npm install again (without running any `fix`, it should work for you.

Thanks -
