### ISSUE TITLE
Exception while running apm@0.0 similiar to Issue 129

### ISSUE THREAD

**Issue by Michael-Dido** [DeborahK/Angular-GettingStarted#131]
Hello,
I am having similar issue.
I have APM working on a virtual machine, But I can't get tit to work an my main development laptop.

npm install
Finds 6 vulnerabilities (1 low, 3 moderate, 2 high)   [Same thing on my virtual machine]

[2020-04-20T20_37_12_529Z-debug.log](https://github.com/DeborahK/Angular-GettingStarted/files/4506040/2020-04-20T20_37_12_529Z-debug.log)

I have tried reinstalling nodejs. Did not help.

What do I do now?

**Comment by DeborahK** [comment]
You can ignore the vulnerabilities warnings. These are in the developer tools that will never be deployed to production.

Be sure you do *NOT* run a fix. That will update some of the packages without correctly updating all of them.  (If you did run a fix, start the process over and don't run the fix.)

If you don't run a fix, everything should work fine.

**Comment by Michael-Dido** [comment]
Deborah,

Thank you for your quick reply.
However:
Uninstall nodejs
Reboot
Install nodejs

In the APM folder, I deleted the node_modules and package-lock.json
Npm install
Got the same : found 6 vulnerabilities (1 low, 3 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

I did not fix anything
Npm start

[cid:image001.png@01D61741.191F67D0]

The angular-errors.log :
[error] Error: error TS5058: The specified path does not exist: 'C:/Users/Micha/source/Workspaces/MyCopyOfAngularGettingStarted/tsconfig.json'.

    at Object.readTsconfig (C:\Users\Micha\source\Workspaces\MyCopyOfAngularGettingStarted\APM\node_modules\@angular-devkit\build-angular\src\angular-cli-files\utilities\read-tsconfig.js:27:15)
    at generateWebpackConfig (C:\Users\Micha\source\Workspaces\MyCopyOfAngularGettingStarted\APM\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:18:38)
    at generateBrowserWebpackConfigFromWorkspace (C:\Users\Micha\source\Workspaces\MyCopyOfAngularGettingStarted\APM\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:96:12)
    at Object.generateBrowserWebpackConfigFromContext (C:\Users\Micha\source\Workspaces\MyCopyOfAngularGettingStarted\APM\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:107:26)
    at async setup (C:\Users\Micha\source\Workspaces\MyCopyOfAngularGettingStarted\APM\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:73:37)


I'm confused.


Because of these Issues I wants to see if I could get anything to work on this machine.
I followed the steps @ https://angular.io/cli and this worked fine.  Did that load something that might be in conflict with your tutorial?

Thank you again for any help you can provide.
Michael

**Comment by DeborahK** [comment]
This path from your error message doesn't look correct: `'C:/Users/Micha/source/Workspaces/MyCopyOfAngularGettingStarted/tsconfig.json'.`

My files are all in an `APM` folder. Or if you didn't rename it: `APM-Start`.

Be sure you have navigated down to the APM folder containing the package.json and tsconfig.json before you run `npm install` or `npm start`.

Let me know if that helps. If not, a few screen shots of your folder structure may be helpful.

**Comment by DeborahK** [comment]
If you want to proceed without trying to get it to install, you can do as the tutorial does and use Stackblitz instead of downloading and installing anything.

The instructions for using Stackblitz with my files are here: https://github.com/DeborahK/Angular-GettingStarted#stackblitz

**Comment by Michael-Dido** [comment]
The problem is it’s looking 1 level up for the tsconfig.json.
I copied your APM-Start to another folder 1 level up, and get same behavior.
The terminal prompt shows I’m in the right directory  (PS C:\Users\Micha\source\Workspaces\APM>) when I do the npm install and npm start.

What process(code) is setting that path wrong?

I will try your other Stackblitz suggestion later today.

Thanks
Michael

**Comment by DeborahK** [comment]
Glad you resolved the issue.

Regarding the player, I had that happen to me last week as well. I just logged out and logged back in and then it was fine.

If the problem persists, contact support@pluralsight.com.

(I have no control/access to provide assistance with Pluralsight's player.)

**Comment by DeborahK** [comment]
I'm closing this issue at this time.

Please reach out if you still have issues with the code.
