### ISSUE TITLE
id issue

### ISSUE THREAD

**Issue by SOG-web** [DeborahK/Angular-GettingStarted#138]
getProduct(id: number) {
    this.productService.getProductsFromServer**(id)**.subscribe({
      next: (productFromServer) => (this.products = productFromServer),
      error: (err) => (this.errorMessage = err),
    });
  }
ERROR in src/app/products/product-detail.component.ts:31:47 - error TS2554: Expected 0 arguments, but got 1.

    31     this.productService.getProductsFromServer**(id).**subscribe({

**Comment by DeborahK** [comment]
Did we resolve this in the discussion group for the Angular: Getting Started course? I'm going to close this issue. Please reopen it if this was not resolved.
