### ISSUE TITLE
Angular npm start error

### ISSUE THREAD

**Issue by barrantesj1952** [DeborahK/Angular-GettingStarted#147]
when I try to run the application with npm start I got an error.
Searching in google I found a solution "delete node_modules", "npm install" but I keep getting the error below.
roberto@Administrators-MacBook-Pro APM % npm start       

> apm@0.0.0 start /Users/Shared/Previously Relocated Items/Security/Repositories/TypeScript/GettingStartedRB/APM
> ng serve -o

The serve command requires to be run in an Angular project, but a project definition could not be found.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apm@0.0.0 start: `ng serve -o`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apm@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/roberto/.npm/_logs/2021-01-25T19_40_58_333Z-debug.log
roberto@Administrators-MacBook-Pro APM % 

-------------------------------------------------------
log error
-------------------------------------------------------0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.11
3 info using node@v10.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle apm@0.0.0~prestart: apm@0.0.0
6 info lifecycle apm@0.0.0~start: apm@0.0.0
7 verbose lifecycle apm@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle apm@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/Shared/Previously Relocated Items/Security/Repositories/TypeScript/GettingStartedRB/APM/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
9 verbose lifecycle apm@0.0.0~start: CWD: /Users/Shared/Previously Relocated Items/Security/Repositories/TypeScript/GettingStartedRB/APM
10 silly lifecycle apm@0.0.0~start: Args: [ '-c', 'ng serve -o' ]
11 silly lifecycle apm@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle apm@0.0.0~start: Failed to exec start script
13 verbose stack Error: apm@0.0.0 start: `ng serve -o`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid apm@0.0.0
15 verbose cwd /Users/Shared/Previously Relocated Items/Security/Repositories/TypeScript/GettingStartedRB/APM
16 verbose Darwin 20.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.16.1
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error apm@0.0.0 start: `ng serve -o`
22 error Exit status 1
23 error Failed at the apm@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by DeborahK** [comment]
A few things to try:

Things to try:
1) Did you run `npm install` successfully? The project files must first be *installed* before you can use *npm start* to start the project.

2) Ensure that there is a package.json file in the folder.

3) Try  cleaning your npm cache:
 - Run `npm cache verify`
 - Delete your node_modules folder and package-lock.json file (if they exist in the project folder)
 - Run `npm install` again.

4) If that doesn't work, double check your version of npm. Ensure you install the LTS version of node (with npm) and not the "current" version, which seems to have more issues. Then repeat #1.
NOTE: I have node v12. Looks like you have v10. Though the Angular docs say "node": ">= 10.13.0", so your version should work.

5) I've heard that some people with very long paths to the Angular files have had trouble in the past: `/Users/Shared/Previously Relocated Items/Security/Repositories/TypeScript/GettingStartedRB/APM` You could try moving the code to another folder with a shorter path and then repeat #1.

Let me know if any of these options worked for you.
All the best -

**Comment by DeborahK** [comment]
Did you have any luck with this? I'm closing it for now. Feel free to re-open if none of the above resolved your issue.
