### ISSUE TITLE
When creating a new project I get this error

### ISSUE THREAD

**Issue by CarlosArroyoez** [DeborahK/Angular-GettingStarted#153]
\ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: app@0.0.0
npm ERR! Found: jasmine-core@3.6.0
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.7.1" from karma-jasmine-html-reporter@1.6.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\PC1\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PC1\AppData\Local\npm-cache\_logs\2021-05-08T22_47_36_556Z-debug.log
× Package install failed, see above.

Angular CLI: 11.2.12
Node: 14.16.1
OS: win32 x64

I would like to know if someone knows why this happens and to be able to solve it

**Comment by DracoStrongborn** [comment]
Same for me. This is running on a Raspberry Pi with Raspbian for me.

**Comment by DeborahK** [comment]
The code was updated to Angular v12 on July 9th. Does this exact error still occur now with the updated Angular version?

**Comment by DeborahK** [comment]
I'm closing this for now. If you are still experiencing this issue, please reopen.
