### ISSUE TITLE
Images not displaying on the initial setup thro Pluralsight

### ISSUE THREAD

**Issue by cpkrish123** [DeborahK/Angular-GettingStarted#156]
I have copied the images to my local folder
but they do not show up
any secret to making them show up on the browser?

My browser is Chrome

**Comment by cpkrish123** [comment]
Ignore this. 
I was using .jpg per your code on the pages
did not realize that the images were .png images instead.

**Comment by DeborahK** [comment]
Thank you for your post.

Regarding: `I was using .jpg per your code on the pages` Could you be more specific about what "pages" you are referring to? If I have instructions that are not longer correct, I'd like to ensure that I update them.

Thanks again!
