### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by Fillrobs** [DeborahK/Angular-GettingStarted#157]
I am using Windows 10 - I followed the instructions carefully - when I run npm start I bet a blank window with no errors and it just states waiting for localhost in the bottom of the Chrome browser window.  I tried creating a new one - following other more basic instructions - same issue - any ideas?

**Comment by DeborahK** [comment]
Did `npm install` work without any errors?

Are there any messages in your VS Code terminal window?

If you open the Chrome dev tools (F12), do you see any errors in the console?

**Comment by Fillrobs** [comment]
Thanks for the quick response - I went through the installer again and the 1st time a new CMD window opened with a click to continue - I did that 3 times and nothing happened - I assumed it had finished - this was my issue - I believe I had some permissions issues with my temp folder (although no error message appeared - I came to that conclusion after a bit of googling) - I fixed that - I tried again and after clicking to continue it installed Python and whatever else it did and it now works - thanks again
