### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by PatrickKwinten** [DeborahK/Angular-GettingStarted#55]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.11
3 info using node@v4.8.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart apm@0.0.0
6 info start apm@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info apm@0.0.0 Failed to exec start script
9 verbose stack Error: apm@0.0.0 start: `ng serve -o`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:862:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid apm@0.0.0
11 verbose cwd /home/patrick/Downloads/Angular-GettingStarted-master/APM-Final
12 error Linux 4.4.0-78-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
14 error node v4.8.3
15 error npm  v2.15.11
16 error code ELIFECYCLE
17 error apm@0.0.0 start: `ng serve -o`
17 error Exit status 1
18 error Failed at the apm@0.0.0 start script 'ng serve -o'.
18 error This is most likely a problem with the apm package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ng serve -o
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs apm
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls apm
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by DeborahK** [comment]
The above output shows your version:
2 info using npm@2.15.11
3 info using node@v4.8.3

As stated in the course, you need *at least* npm v3 ... but newer would be better. (I'm using npm 4.1.2) Please install the current versions of node and npm and try again.

**Comment by dastangoo** [comment]
Can you help about this error?
-----------------------------------------------------
superuser:Hamed-MBP APM $ sudo npm start

> apm@0.0.0 start /Users/superuser/APM
> ng serve -o

Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (/Users/superuser/APM/node_modules/@angular/cli/tasks/serve.js:21:63)
    at check_port_1.checkPort.then.port (/Users/superuser/APM/node_modules/@angular/cli/commands/serve.js:110:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/superuser/.nvm/versions/node/v6.11.2/bin/node" "/Users/superuser/.nvm/versions/node/v6.11.2/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! apm@0.0.0 start: `ng serve -o`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apm@0.0.0 start script 'ng serve -o'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the apm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve -o
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs apm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls apm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/superuser/APM/npm-debug.log

**Comment by DeborahK** [comment]
There are several things that can cause this error as discussed here: https://github.com/angular/angular-cli/issues/4736

The most common are an older version of the CLI or a problem with the CLI configuration file. Are you running this from the folder containing the angular cli config? Did you run `npm install` first without any errors?

**Comment by nbarcham** [comment]
Hi Deborah,
I am getting the below error when trying to preform npm start
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart apm@0.0.0
6 info start apm@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info apm@0.0.0 Failed to exec start script
9 verbose stack Error: apm@0.0.0 start: `ng serve -o`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid apm@0.0.0
11 verbose cwd C:\Users\naser.m.barcham\Documents\Projects\Angular-GettingStarted-master\APM
12 error Windows_NT 10.0.14393
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.6.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error apm@0.0.0 start: `ng serve -o`
17 error Exit status 1
18 error Failed at the apm@0.0.0 start script 'ng serve -o'.
18 error This is most likely a problem with the apm package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ng serve -o
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs apm
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls apm
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
 not sure why I do have the latest versions installed

**Comment by DeborahK** [comment]
From the Angular CLI docs: 

> Both the CLI and generated project have dependencies that require Node 6.9.0 or higher, together with NPM 3 or higher.

From your error message above:

> 2 info using npm@2.15.9
> 3 info using node@v4.6.0
