### ISSUE TITLE
app.module.ts  Routing Map in Video not same as in Repository

### ISSUE THREAD

**Issue by underwater** [DeborahK/Angular-GettingStarted#56]
Great Course !
I've noticed that the repository code (final version) defines below routes in the app.module.ts 
`outerModule.forRoot([
        { path: 'welcome', component: WelcomeComponent },
        { path: '', redirectTo: 'welcome', pathMatch: 'full'},
        { path: '**', redirectTo: 'welcome', pathMatch: 'full'}
    ]),

In your video however, there are two more entries, 
`RouterModule.forRoot([
{ path: 'products', component: ProductListComponent },
{ path: 'products/:id', component: ProductDetailComponent },
....
`

surprisingly navigation still works exactly as described in the video in spite of the fact that the above two routes are missing !!!

Is there an explanation as to why the navigation still works just fine in spite of any route definitions to these two components ?

**Comment by DeborahK** [comment]
Thank you!

Have you watched the entire course? In the course module on Angular modules I demonstrate how to build a feature module and move routes into the feature module. So these two product routes are in a new Product module.

These routes are then pulled in when the ProductModule is included in the imports array of the AppModule.

Make sense? I'm closing this issue. Feel free to reopen it if you still have a question about this.

**Comment by underwater** [comment]
Hi Deborah
Thanks so much for your quick response, , I hadn't finished the course, and
your explanation clarifies this issues,
Thanks a lot, it is a great course,
Fares
