### ISSUE TITLE
rxjs

### ISSUE THREAD

**Issue by lakshmi9999** [DeborahK/Angular-GettingStarted#57]
ERROR in C:/Users/sailu/Desktop/Angular-GettingStarted-master/APM/src/app/products/product.service.ts (3,26): Cannot find module '@rxjs/Observable
![screenshot 4](https://user-images.githubusercontent.com/31414304/29944612-2128b590-8e6c-11e7-8eaa-cc13ff6b72ff.png)

**Comment by DeborahK** [comment]
There should be no @ sign here:

`import { Observable } from 'rxjs/Observable';`

**Comment by lakshmi9999** [comment]
Thank you. got it!!
