### ISSUE TITLE
angular 2 or 4

### ISSUE THREAD

**Issue by lakshmi9999** [DeborahK/Angular-GettingStarted#59]
Is it angular 4 or 2? What is the difference b/w it

**Comment by DeborahK** [comment]
The current version of this course is 4.3. 

There is not much different between Angular 2 and Angular 4. A few key things:

1) There is now a paramMap property when working with routing.
2) Angular 4.3 introduced a new HttpClient to simplify accessing a back-end server.
3) At the same time as Angular 4, the Angular CLI 1.0 was released.
4) Performance and size improvements

There are a few other changes that you can find listed here:

http://angularjs.blogspot.com/2017/03/angular-400-now-available.html 

https://blog.angular.io/angular-4-3-now-available-8d57b57eb5a8
