### ISSUE TITLE
Error msg : Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by balco** [DeborahK/Angular-GettingStarted#60]
error: Cannot read property 'toLowerCase' of undefined,

**Comment by DeborahK** [comment]
Not much to go on here. The message is telling you that whatever object you have to the left of the `toLowerCase` is undefined, so not yet set.

**Comment by DeborahK** [comment]
Have you resolved this issue? I'm closing it. Feel free to re-open it if you still have an issue.

**Comment by simeyla** [comment]
To try to debug this, enable the 'Pause on caught exceptions' in Chrome.
However, this will give you a bazillion errors - so if you think you know roughly where in your code it is coming from wrap the call with `setTimeout(() => {...}, 3000` and during the timeout click the 'Pause on caught exceptions'.

For me I had an Http interceptor that was getting no URL for some reason. I was then able to work backwards to fix the issue. For me I had `this.filename = "http://....."` but `filename()` was a setter with no getter - so when I did an HTTP request `this.filename` was always null!

![image](https://user-images.githubusercontent.com/3656278/43872109-ddb2add0-9b34-11e8-8fe1-2fd42fbcfc3f.png)
