### ISSUE TITLE
section 7 (More on Components) - Building Custom Pipes

### ISSUE THREAD

**Issue by sipuxd** [DeborahK/Angular-GettingStarted#63]
**I keep getting the following console error:** 
 "compiler.es5.js:1694 Uncaught Error: Template parse errors:
The pipe 'convertToSpaces' could not be found ("     </td>
                        <td>{{ product.productName}}</td>
                        <td>{{ [ERROR ->]product.productCode | lowercase | convertToSpaces: '-' }}</td>
                        <td>{{ product"): ng:///AppModule/ProductListComponent.html@45:31
    at syntaxError (compiler.es5.js:1694)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (compiler.es5.js:12791)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (compiler.es5.js:26994)
    at compiler.es5.js:26913
    at Set.forEach (<anonymous>)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (compiler.es5.js:26913)
    at compiler.es5.js:26800
    at Object.then (compiler.es5.js:1683)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (compiler.es5.js:26799)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (compiler.es5.js:26728)"

**-- convert-to-spaces.pipe.ts file code is below --**

import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
    name
})

export class ConvertToSpacesPipe implements PipeTransform {

        transform(value: string, character: string): string {
            return value.replace(character, ' ');
        }

}

**-- app.module.ts file code is below --**

import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';

import { ProductListComponent } from './Products/product-list.component'
import { ConvertToSpacesPipe } from './shared/convert-to-spaces.pipe'

@NgModule({
  declarations: [
    AppComponent,
    ProductListComponent,
    ConvertToSpacesPipe
  ],
  imports: [
    BrowserModule,
    FormsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

**-- product-list.component.html file code is below 
(The html turns into a table on here. The pipe is under the Code column though) --**

<div class='panel panel-primary'>
    <div class='panel-heading'>
        {{pageTitle}}
    </div>
    <div class='panel-body'>
        <div class ='row'>
        <div class='col-md-2'>Filter by:</div>
        <div class='col-md-4'>
            <input type='text' 
                    [(ngModel)]='listFilter' />
        </div>
    </div>
    <div class='row'>
        <div class='col-md-6'>
            <h3>Filtered by: {{listFilter}} </h3>
        </div>
    </div>
    <div class='table-responsive'>
        <table  class='table'
                *ngIf='products && products.length'>
            <thead>
                <tr>
                    <th>
                        <button class='btn btn-primary'
                            (click)='toggleImage()'>
                            {{showImage ? 'Hide' : 'Show'}} Image
                        </button>
                    </th>
                    <th>Product</th>
                    <th>Code</th>
                    <th>Available</th>
                    <th>Price</th>
                    <th>5 Star Rating</th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor='let product of products'>
                        <td>
                            <img *ngIf='showImage'
                                [src]='product.imageUrl'
                                [title]='product.productName'
                                [style.width.px]='imageWidth'
                                [style.margin.px]='imageMargin'>
                        </td>
                        <td>{{ product.productName}}</td>
                        <td>{{ product.productCode | lowercase | convertToSpaces: '-' }}</td>
                        <td>{{ product.releaseDate }}</td>
                        <td>{{ product.price | currency:'USD':true:'1.2-2' }}</td>
                        <td>{{ product.starRating }}</td>
                    </tr>
            </tbody>
        </table>
    </div>
    </div>
</div>

**Comment by DeborahK** [comment]
It looks like this code:

```
@pipe({
name
})
```

Is missing the actual name. Hence it cannot find it. This code should look like this:

```
@Pipe({
    name: 'convertToSpaces'
})
```

**Comment by sipuxd** [comment]
haha, oops. Yeah I just saw that now.  I'm impressed by your quick response!!! :)
