### ISSUE TITLE
Refactoring Routing

### ISSUE THREAD

**Issue by sipuxd** [DeborahK/Angular-GettingStarted#65]
Architecturally, where would you suggest to put the app-routing.module.ts file and product-routing.module.ts file? Would you suggest to create new folder for each one?

**Comment by DeborahK** [comment]
I normally put the app-routing.module.ts file in the same location as the app.module.ts file which is in the app folder.

I would put any module files for products in the root products folder.

Hope that helps.

**Comment by sipuxd** [comment]
Yep, perfect.  Thank you! :)
