### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: StaticInjectorError[HttpClient]: 

### ISSUE THREAD

**Issue by srisrim** [DeborahK/Angular-GettingStarted#69]
ERROR Error: Uncaught (in promise): Error: StaticInjectorError[HttpClient]:

**Comment by DeborahK** [comment]
Any context for this? When do you see this error? Are you attempting to mix HttpModule and HttpClientModule in your application?

**Comment by srisrim** [comment]
Yes

**Comment by DeborahK** [comment]
I'm closing this. If you have more information about this error we can reopen and I'll look into it further.
