### ISSUE TITLE
problem with npm install

### ISSUE THREAD

**Issue by juanregules** [DeborahK/Angular-GettingStarted#70]
when i put in the console "npm install". the programm tell me this:
npm : El término 'npm' no se reconoce como nombre de un cmdlet, función, archivo de script o
programa ejecutable. Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso,
compruebe que dicha ruta es correcta e inténtelo de nuevo.
En línea: 1 Carácter: 1
+ npm start
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

//sorry for the spanish. can someone help me please??

**Comment by philippfx** [comment]
(1) Download node.js that suits your operating system from https://nodejs.org/en/download/, (2) install it, (3) reboot and (4) try the command "npm install" again.

This worked for me.

Best regards

**Comment by DeborahK** [comment]
Did Philip's suggestion help you?

**Comment by DeborahK** [comment]
I'm closing this. If you have more information, we can reopen it.

**Comment by AlberthPerezM** [comment]
Yo tambien he tenido problemas

**Comment by DeborahK** [comment]
One of the most common issues with npm is installing the wrong version of node.

Be sure to install the *LTS* version and NOT the *current* version of node. Using the *current* version is not supported and doesn't work with Angular.

1) Uninstall your current version of node.
2) Install the LTS version of node from here: https://nodejs.org/en/download/
3) Delete your node_modules folder and your package-lock.json file.
4) Run npm install again.

If that doesn't work, please be specific on the exact problem you are having.

Hope this helps!

**Comment by DeborahK** [comment]
Are you trying to upload your code to GitHub? If so, you need to create a GitHub account. Then follow the instructions here: https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-new-repository
