### ISSUE TITLE
Cannot read property 'config' of null

### ISSUE THREAD

**Issue by stev03945** [DeborahK/Angular-GettingStarted#71]
I have just run npm install and then tried npm start. I get an error "Cannot read property 'config' of null"

Any ideas on that? I'm using MAC

**Comment by hseritt** [comment]
I got the same thing on an Ubuntu 16.04 system.

**Comment by DeborahK** [comment]
Do you have a .angular-cli.json file in your folder?On some systems this file is hidden and not included when copying files.

**Comment by anoopsingh** [comment]
@hseritt @stev03945 If you copy .angular-cli.json file in your root folder , you will not get that error, i was running into same issue , but @DeborahK comment helped me, that issue can be closed

**Comment by DeborahK** [comment]
I'm assuming you've resolved this at this point. I'm closing this.
