### ISSUE TITLE
Error when I run npm start in APM-Start - not iterable

### ISSUE THREAD

**Issue by rodsantest1** [DeborahK/Angular-GettingStarted#72]
Update: It works fine on Chrome!

Error when I run npm start in APM-Start - not iterable
node --version 6.11.4
vs code 1.17.1
IE 11
![start issue](https://user-images.githubusercontent.com/30728121/34087271-fdf69d36-e36f-11e7-9155-0e32d6ec855d.PNG)

**Comment by DeborahK** [comment]
Have you un-commented all of the polyfills needed for IE 11?
