### ISSUE TITLE
problem with downloading .vscode file for APMStart

### ISSUE THREAD

**Issue by aidancousins** [DeborahK/Angular-GettingStarted#73]
The .vscode file does not download on an OS 10.12.4 is this because of compatibility issues?

**Comment by DeborahK** [comment]
A file that starts with a "." is often viewed as a "System" file on a mac. So it may be hidden.

You don't really need it. The only thing I have set up in there is automatic saving, and you can add that yourself.

As long as you *do* have the .angular-cli.json file.
