### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by lacourciere** [DeborahK/Angular-GettingStarted#74]
I am receiving an error on npm start.  Below are the terminal text and log file:

> ng serve -o

module.js:538
    throw err;
    ^

Error: Cannot find module 'abbrev'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\akcook\Desktop\Angular\Angular-GettingStarted-master\APM\node_modules\
nopt\lib\nopt.js:10:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apm@0.0.0 start: `ng serve -o`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apm@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Logfile**:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle apm@0.0.0~prestart: apm@0.0.0
6 info lifecycle apm@0.0.0~start: apm@0.0.0
7 verbose lifecycle apm@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle apm@0.0.0~start: PATH: ....
10 silly lifecycle apm@0.0.0~start: Args: [ '/d /s /c', 'ng serve -o' ]
11 silly lifecycle apm@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle apm@0.0.0~start: Failed to exec start script
13 verbose stack Error: apm@0.0.0 start: `ng serve -o`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid apm@0.0.0
15 verbose cwd C:\Users\Desktop\Angular\Angular-GettingStarted-master\APM
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error apm@0.0.0 start: `ng serve -o`
22 error Exit status 1
23 error Failed at the apm@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by DeborahK** [comment]
Please see this: https://github.com/angular/angular-cli/issues/5588

**Comment by bhavik2312** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\solanbha\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle apm@0.0.0~prestart: apm@0.0.0
6 info lifecycle apm@0.0.0~start: apm@0.0.0
7 verbose lifecycle apm@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle apm@0.0.0~start: PATH: C:\Users\solanbha\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\bhavik\myangular\APM\node_modules\.bin;C:\Program Files\Microsoft MPI\Bin\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files (x86)\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Users\solanbha\AppData\Local\Microsoft\WindowsApps;C:\Users\solanbha\AppData\Roaming\npm
9 verbose lifecycle apm@0.0.0~start: CWD: D:\bhavik\myangular\APM
10 silly lifecycle apm@0.0.0~start: Args: [ '/d /s /c', 'ng serve -o' ]
11 silly lifecycle apm@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle apm@0.0.0~start: Failed to exec start script
13 verbose stack Error: apm@0.0.0 start: `ng serve -o`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\solanbha\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\solanbha\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid apm@0.0.0
15 verbose cwd D:\bhavik\myangular\APM
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\solanbha\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error apm@0.0.0 start: `ng serve -o`
22 error Exit status 1
23 error Failed at the apm@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by bhavik2312** [comment]
it's solved just need to type npm update and all are working awesome

**Comment by DeborahK** [comment]
Glad you resolved the issue.

**Comment by CiprianSavoiu** [comment]
same problem here.... tried the npm update. does nothing, tried the link angular-cli
i'm using npm 6.13.1

**Comment by DeborahK** [comment]
There are several errors mentioned here ... what error specifically are you getting?

**Comment by adurlea** [comment]
> same problem here.... tried the npm update. does nothing, tried the link angular-cli
> i'm using npm 6.13.1

Hello i'm using npm 6.13.2 on Linux. 
Try after npm-update to update also the dependencies for your version of npm and Angular Cli:

  npm install @angular-devkit/build-angular
  npm install @angular/cli
  npm install @angular/compiler-cli

This worked for me.

**Comment by CiprianSavoiu** [comment]
![image](https://user-images.githubusercontent.com/20278263/70982973-e0bbef80-20af-11ea-863c-b591509fe8d5.png)
This is the error i'm getting

**Comment by DeborahK** [comment]
Googling this error suggested that it may be due to a missing package.

Try deleting your node_modules folder and your package.-lock.json file, cleaning your npm cache and trying npm install again.

There is also a discussion of this error here: https://github.com/webpack/webpack/issues/6323

Let me know if that helps.

**Comment by CiprianSavoiu** [comment]
Thank you for the prompt answer.

I deleted the node_modules and package-lock.json file and did a new npm install
After looking more in detail to the command line messages it seems the webpack it's not installed properly.
I will try to dig this up 
![image](https://user-images.githubusercontent.com/20278263/70987505-f0d7cd00-20b7-11ea-8d32-03d5c57a5148.png)

**Comment by CiprianSavoiu** [comment]
Unfortunately, no solution so far. I will try later on a different computer with a clean install of node

**Comment by DeborahK** [comment]
In the mean time ... you could proceed with the course using Stackblitz: 

https://github.com/DeborahK/Angular-GettingStarted#stackblitz

That doesn't require any installation.

**Comment by CiprianSavoiu** [comment]
Thanks for the link to Stackblitz. I found it as well in the course but not being able to run it on my computer was really annoying but it is finally sorted now.
The problem was to environment variables. I found this and after adding some of the missing ones worked like a charm.
![image](https://user-images.githubusercontent.com/20278263/71081664-93ab4c80-2187-11ea-8f7a-8126733a9462.png)

link also here: https://github.com/facebook/create-react-app/issues/6985 it is to react though but I used the environment paths bit out of it :)

**Comment by saitejap1234** [comment]
> I am receiving an error on npm start. Below are the terminal text and log file:
> 
> > ng serve -o
> 
> module.js:538
> throw err;
> ^
> 
> Error: Cannot find module 'abbrev'
> at Function.Module._resolveFilename (module.js:536:15)
> at Function.Module._load (module.js:466:25)
> at Module.require (module.js:579:17)
> at require (internal/module.js:11:18)
> at Object. (C:\Users\akcook\Desktop\Angular\Angular-GettingStarted-master\APM\node_modules
> nopt\lib\nopt.js:10:14)
> at Module._compile (module.js:635:30)
> at Object.Module._extensions..js (module.js:646:10)
> at Module.load (module.js:554:32)
> at tryModuleLoad (module.js:497:12)
> at Function.Module._load (module.js:489:3)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! apm@0.0.0 start: `ng serve -o`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the apm@0.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> **Logfile**:
> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
> 1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
> 1 verbose cli 'start' ]
> 2 info using npm@5.5.1
> 3 info using node@v8.9.3
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle apm@0.0.0~prestart: apm@0.0.0 6 info lifecycle apm@0.0.0~start: apm@0.0.0
> 7 verbose lifecycle apm@0.0.0~start: unsafe-perm in lifecycle true 8 verbose lifecycle apm@0.0.0~start: PATH: ....
> 10 silly lifecycle apm@0.0.0~start: Args: [ '/d /s /c', 'ng serve -o' ] 11 silly lifecycle apm@0.0.0~start: Returned: code: 1 signal: null
> 12 info lifecycle apm@0.0.0~start: Failed to exec start script
> 13 verbose stack Error: apm@0.0.0 start: `ng serve -o`
> 13 verbose stack Exit status 1
> 13 verbose stack at EventEmitter. (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
> 13 verbose stack at emitTwo (events.js:126:13)
> 13 verbose stack at EventEmitter.emit (events.js:214:7)
> 13 verbose stack at ChildProcess. (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack at emitTwo (events.js:126:13)
> 13 verbose stack at ChildProcess.emit (events.js:214:7)
> 13 verbose stack at maybeClose (internal/child_process.js:925:16)
> 13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 14 verbose pkgid apm@0.0.0
> 15 verbose cwd C:\Users\Desktop\Angular\Angular-GettingStarted-master\APM
> 16 verbose Windows_NT 6.1.7601
> 17 verbose argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
> 18 verbose node v8.9.3
> 19 verbose npm v5.5.1
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error apm@0.0.0 start: `ng serve -o`
> 22 error Exit status 1
> 23 error Failed at the apm@0.0.0 start script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

Go to search bar and write environment variables. You should see an option to called edit system environment variables or something similar.
Under the Advanced section there is a enivronment variable button. click it.
After that you will see an option named path click on it.
click add button and add following directory C:\Windows\System32.
close down your editor and restart your command terminal. Problem should be resolved now

**Comment by saitejap1234** [comment]
.
