### ISSUE TITLE
Index page html content showing instead of component html

### ISSUE THREAD

**Issue by santoshbantu743** [DeborahK/Angular-GettingStarted#79]
Hi Deborah,
Firstly Thanks for creating a great video!!
As per your pluralsight video for Angular 2 getting started, i followed the steps to install, configure and run APM-Start. i see the the browser shows index.html content instead of app.Component.html. When i change something index.html it reflects on the browser.
I am assuming the the video is old and code is updated to show index.html by default.

Regards,
Santosh

**Comment by DeborahK** [comment]
I just updated the course in August of 2017 to Angular 4.3 ... so no ... the video is not old.

The browser should show the index.html content with the app.component.html content within it.

This is what you should see when starting up the application:

![image](https://user-images.githubusercontent.com/7987365/36048983-00bc7d42-0d96-11e8-8744-5d784ddf4ab4.png)

**Comment by santoshbantu743** [comment]
Sure. Then i need to check if I am doing something wrong. Haven't updated anything the solution, just running it. Does any installation failure cause this ?
Below is the screenshot for your reference though.

![angular-gettingstarted](https://user-images.githubusercontent.com/27299004/36049862-558ec3ea-0db2-11e8-9b06-3b9f4ad650e7.PNG)

**Comment by santoshbantu743** [comment]
Yes you are absolutely right!! I was using google chrome but it wasn't the latest update as I am working on developer VM and it has no internet connectivity. i update the chrome using offline installer and it worked.  Thanks for your prompt response.

![success-latestchrome](https://user-images.githubusercontent.com/27299004/36050522-ca362ce0-0db4-11e8-83a2-689996a38ca0.PNG)

**Comment by DeborahK** [comment]
Glad you were able to resolve the issue!
