### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by GirishSrinivas** [DeborahK/Angular-GettingStarted#81]
Girish-MacBook:APM Girish$ npm start

> apm@0.0.0 start /Users/Girish/Documents/GitRepo/Angular-GettingStarted/APM
> ng serve -o

Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (/Users/Girish/Documents/GitRepo/Angular-GettingStarted/APM/node_modules/@angular/cli/tasks/serve.js:21:63)
    at check_port_1.checkPort.then.port (/Users/Girish/Documents/GitRepo/Angular-GettingStarted/APM/node_modules/@angular/cli/commands/serve.js:110:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apm@0.0.0 start: `ng serve -o`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apm@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Log file
--------

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle apm@0.0.0~prestart: apm@0.0.0
6 info lifecycle apm@0.0.0~start: apm@0.0.0
7 verbose lifecycle apm@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle apm@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/Girish/Documents/GitRepo/Angular-GettingStarted/APM/node_modules/.bin:/Users/Girish/Documents/Software/apache-maven-3.5.0/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/mysql/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
9 verbose lifecycle apm@0.0.0~start: CWD: /Users/Girish/Documents/GitRepo/Angular-GettingStarted/APM
10 silly lifecycle apm@0.0.0~start: Args: [ '-c', 'ng serve -o' ]
11 silly lifecycle apm@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle apm@0.0.0~start: Failed to exec start script
13 verbose stack Error: apm@0.0.0 start: `ng serve -o`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid apm@0.0.0
15 verbose cwd /Users/Girish/Documents/GitRepo/Angular-GettingStarted/APM
16 verbose Darwin 17.4.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error apm@0.0.0 start: `ng serve -o`
22 error Exit status 1
23 error Failed at the apm@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by DeborahK** [comment]
This error is almost always caused by a missing .angular-cli.json file. This file should be in your root (APM) folder.

Are you using a Mac? If so, file names that begin with a "." (dot) are often seen as system files and are hidden or not copied. Go back to the repository and ensure that you copy this file to the (APM) folder and that it is not hidden.

Let me know if that solves it and we can close this issue.

**Comment by GirishSrinivas** [comment]
Yes Deborah, it was hidden in the folder.
it solved the issue after copying the file.
you can close the issue.

Thank you so much
