### ISSUE TITLE
Having trouble getting npm start to run on my mac

### ISSUE THREAD

**Issue by stigall88** [DeborahK/Angular-GettingStarted#83]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle apm@0.0.0~prestart: apm@0.0.0
6 info lifecycle apm@0.0.0~start: apm@0.0.0
7 verbose lifecycle apm@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle apm@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/owner/Repos/github/Angular-GettingStarted/APM/node_modules/.bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/apache-maven-3.5.0/bin:/opt/apache-maven-3.5.0/bin
9 verbose lifecycle apm@0.0.0~start: CWD: /Users/owner/Repos/github/Angular-GettingStarted/APM
10 silly lifecycle apm@0.0.0~start: Args: [ '-c', 'ng serve -o' ]
11 silly lifecycle apm@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle apm@0.0.0~start: Failed to exec start script
13 verbose stack Error: apm@0.0.0 start: `ng serve -o`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid apm@0.0.0
15 verbose cwd /Users/owner/Repos/github/Angular-GettingStarted/APM
16 verbose Darwin 17.4.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error apm@0.0.0 start: `ng serve -o`
22 error Exit status 1
23 error Failed at the apm@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by DeborahK** [comment]
This is not really providing anything regarding the error. Is there something that appears *before* this log dump?

**Comment by GreenRidingHood** [comment]
Yes, need more information,
there should be more useful information in your terminal

**Comment by Digibel** [comment]
Doesn't work on mac. Can't see .vscode folder as detailed in your tutorial on pluralsight.

**Comment by Digibel** [comment]
getaddrinfo ENOTFOUND localhost
Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apm@0.0.0 start: `ng serve -o`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apm@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/name/.npm/_logs/2018-04-03T14_33_13_980Z-debug.log

**Comment by DeborahK** [comment]
In the blog post associated with this course: https://blogs.msmvps.com/deborahk/category/angular-course-problem-solver

I have an entry specifically about the following error:

>  ‘Cannot read property ‘config’ of null’ on ‘npm start’
> Problem: When typing ‘npm start’, receive the error: ‘Cannot read property ‘config’ of null’.
> 
> This almost always means that you are missing the .angular-cli.json file. If you are using a Mac, this is often because the Mac sees files that begin with “.” (dot) as system files and hides them or won’t copy them if copying a folder.
> 
> Solution: Go back to the original repository and manually copy the .angular-cli.json file into your root (APM) folder. You may need to perform a Command Shift . to show the hidden files.
> 

The same will be true for the .vscode file (though the only thing that has is an auto save setting).
