### ISSUE TITLE
Getting Error after Giving Command npm start on Terminal

### ISSUE THREAD

**Issue by agupta9897** [DeborahK/Angular-GettingStarted#86]
npm ERR! path C:\Users\Akash\Downloads\Angular-GettingStarted-master\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Akash\Downloads\Angular-GettingStarted-master\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Akash\AppData\Roaming\npm-cache_logs\2018-05-01T11_05_10_828Z-debug.log

**Comment by DeborahK** [comment]
Looks like you are trying to install from the wrong folder. Be sure to navigate down to the APM-Start folder before trying to run npm install.

Npm install installs all of the packages defined in the package.json file. And as the message states, there is no package.json file in the folder you are in.

**Comment by amjadhav1982** [comment]
What is this error message? Pl suggest : node_modules\style-loader\addStyles.js(node:9684) UnhandledPromiseRejectionWarning: Error: Exited with code 1
    at ChildProcess.cp.once.code (C:\AngularJS\Learning\Angular-GettingStarted-master\Angular-GettingStarted-master\APM\node_modules\opn\index.js:82:13)
    at Object.onceWrapper (events.js:275:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:947:16)
    at Socket.stream.socket.on (internal/child_process.js:368:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:598:12)
(node:9684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside
of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9684) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 11% building modules 13/23 modules 10 active ...\webpack-dev-server\client\overlay.jswebpack: wait until bundle finished:

**Comment by DeborahK** [comment]
It tells you the error here: "This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch"

Look at whatever code you added most recently and see if you are missing a catch. 

Are you working through the code in my course? If so, where are you in the course?

I'm going to close this issue. For future problems with the code for the course, please post to the course discussion page here: https://app.pluralsight.com/library/courses/angular-2-getting-started-update/discussion

Thanks!
