### ISSUE TITLE
Can't install npm.Can't install NPM !,  Get this error message. Do not understand the proxy setting have been searching for hours. 

### ISSUE THREAD

**Issue by magicishaq** [DeborahK/Angular-GettingStarted#94]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\ishaq\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@6.1.0
3 info using node@v8.11.3
4 verbose npm-session 3a6846b89a3069dd
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall apm@0.0.0
7 info lifecycle apm@0.0.0~preinstall: apm@0.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 29ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 8ms
16 silly install loadAllDepsIntoIdealTree
17 silly fetchPackageMetaData error for @angular/cli@1.2.4 request to https://registry.npmjs.org/@angular%2fcli failed, reason: getaddrinfo ENOTFOUND host host:80
18 silly fetchPackageMetaData error for @angular/compiler-cli@^4.0.0 request to https://registry.npmjs.org/@angular%2fcompiler-cli failed, reason: getaddrinfo ENOTFOUND host host:80
19 silly fetchPackageMetaData error for @angular/language-service@^4.0.0 request to https://registry.npmjs.org/@angular%2flanguage-service failed, reason: getaddrinfo ENOTFOUND host host:80
20 silly fetchPackageMetaData error for @types/jasmine@~2.5.53 request to https://registry.npmjs.org/@types%2fjasmine failed, reason: getaddrinfo ENOTFOUND host host:80
21 silly fetchPackageMetaData error for @types/jasminewd2@~2.0.2 request to https://registry.npmjs.org/@types%2fjasminewd2 failed, reason: getaddrinfo ENOTFOUND host host:80
22 silly fetchPackageMetaData error for @types/node@~6.0.60 request to https://registry.npmjs.org/@types%2fnode failed, reason: getaddrinfo ENOTFOUND host host:80
23 silly fetchPackageMetaData error for jasmine-core@~2.6.2 request to https://registry.npmjs.org/jasmine-core failed, reason: getaddrinfo ENOTFOUND host host:80
24 silly fetchPackageMetaData error for codelyzer@~3.0.1 request to https://registry.npmjs.org/codelyzer failed, reason: getaddrinfo ENOTFOUND host host:80
25 silly fetchPackageMetaData error for jasmine-spec-reporter@~4.1.0 request to https://registry.npmjs.org/jasmine-spec-reporter failed, reason: getaddrinfo ENOTFOUND host host:80
26 silly fetchPackageMetaData error for karma@~1.7.0 request to https://registry.npmjs.org/karma failed, reason: getaddrinfo ENOTFOUND host host:80
27 silly fetchPackageMetaData error for karma-chrome-launcher@~2.1.1 request to https://registry.npmjs.org/karma-chrome-launcher failed, reason: getaddrinfo ENOTFOUND host host:80
28 silly fetchPackageMetaData error for karma-cli@~1.0.1 request to https://registry.npmjs.org/karma-cli failed, reason: getaddrinfo ENOTFOUND host host:80
29 silly fetchPackageMetaData error for karma-coverage-istanbul-reporter@^1.2.1 request to https://registry.npmjs.org/karma-coverage-istanbul-reporter failed, reason: getaddrinfo ENOTFOUND host host:80
30 silly fetchPackageMetaData error for karma-jasmine@~1.1.0 request to https://registry.npmjs.org/karma-jasmine failed, reason: getaddrinfo ENOTFOUND host host:80
31 silly fetchPackageMetaData error for karma-jasmine-html-reporter@^0.2.2 request to https://registry.npmjs.org/karma-jasmine-html-reporter failed, reason: getaddrinfo ENOTFOUND host host:80
32 silly fetchPackageMetaData error for protractor@~5.1.2 request to https://registry.npmjs.org/protractor failed, reason: getaddrinfo ENOTFOUND host host:80
33 silly fetchPackageMetaData error for tslint@~5.3.2 request to https://registry.npmjs.org/tslint failed, reason: getaddrinfo ENOTFOUND host host:80
34 silly fetchPackageMetaData error for ts-node@~3.0.4 request to https://registry.npmjs.org/ts-node failed, reason: getaddrinfo ENOTFOUND host host:80
35 silly fetchPackageMetaData error for typescript@~2.3.3 request to https://registry.npmjs.org/typescript failed, reason: getaddrinfo ENOTFOUND host host:80
36 silly fetchPackageMetaData error for @angular/animations@^4.0.0 request to https://registry.npmjs.org/@angular%2fanimations failed, reason: getaddrinfo ENOTFOUND host host:80
37 silly fetchPackageMetaData error for @angular/compiler@^4.0.0 request to https://registry.npmjs.org/@angular%2fcompiler failed, reason: getaddrinfo ENOTFOUND host host:80
38 silly fetchPackageMetaData error for @angular/common@^4.0.0 request to https://registry.npmjs.org/@angular%2fcommon failed, reason: getaddrinfo ENOTFOUND host host:80
39 silly fetchPackageMetaData error for @angular/core@^4.0.0 request to https://registry.npmjs.org/@angular%2fcore failed, reason: getaddrinfo ENOTFOUND host host:80
40 silly fetchPackageMetaData error for @angular/forms@^4.0.0 request to https://registry.npmjs.org/@angular%2fforms failed, reason: getaddrinfo ENOTFOUND host host:80
41 silly fetchPackageMetaData error for @angular/platform-browser@^4.0.0 request to https://registry.npmjs.org/@angular%2fplatform-browser failed, reason: getaddrinfo ENOTFOUND host host:80
42 silly fetchPackageMetaData error for @angular/http@^4.0.0 request to https://registry.npmjs.org/@angular%2fhttp failed, reason: getaddrinfo ENOTFOUND host host:80
43 silly fetchPackageMetaData error for @angular/platform-browser-dynamic@^4.0.0 request to https://registry.npmjs.org/@angular%2fplatform-browser-dynamic failed, reason: getaddrinfo ENOTFOUND host host:80
44 silly fetchPackageMetaData error for @angular/router@^4.0.0 request to https://registry.npmjs.org/@angular%2frouter failed, reason: getaddrinfo ENOTFOUND host host:80
45 silly fetchPackageMetaData error for core-js@^2.4.1 request to https://registry.npmjs.org/core-js failed, reason: getaddrinfo ENOTFOUND host host:80
46 silly fetchPackageMetaData error for bootstrap@^3.3.7 request to https://registry.npmjs.org/bootstrap failed, reason: getaddrinfo ENOTFOUND host host:80
47 silly fetchPackageMetaData error for rxjs@^5.4.1 request to https://registry.npmjs.org/rxjs failed, reason: getaddrinfo ENOTFOUND host host:80
48 silly fetchPackageMetaData error for zone.js@^0.8.14 request to https://registry.npmjs.org/zone.js failed, reason: getaddrinfo ENOTFOUND host host:80
49 silly fetchPackageMetaData error for @angular/common@^4.0.0 request to https://registry.npmjs.org/@angular%2fcommon failed, reason: getaddrinfo ENOTFOUND host host:80
50 silly fetchPackageMetaData error for @angular/compiler@^4.0.0 request to https://registry.npmjs.org/@angular%2fcompiler failed, reason: getaddrinfo ENOTFOUND host host:80
51 silly fetchPackageMetaData error for @angular/animations@^4.0.0 request to https://registry.npmjs.org/@angular%2fanimations failed, reason: getaddrinfo ENOTFOUND host host:80
52 silly fetchPackageMetaData error for @angular/core@^4.0.0 request to https://registry.npmjs.org/@angular%2fcore failed, reason: getaddrinfo ENOTFOUND host host:80
53 silly fetchPackageMetaData error for @angular/http@^4.0.0 request to https://registry.npmjs.org/@angular%2fhttp failed, reason: getaddrinfo ENOTFOUND host host:80
54 silly fetchPackageMetaData error for @angular/forms@^4.0.0 request to https://registry.npmjs.org/@angular%2fforms failed, reason: getaddrinfo ENOTFOUND host host:80
55 silly fetchPackageMetaData error for @angular/platform-browser@^4.0.0 request to https://registry.npmjs.org/@angular%2fplatform-browser failed, reason: getaddrinfo ENOTFOUND host host:80
56 silly fetchPackageMetaData error for @angular/platform-browser-dynamic@^4.0.0 request to https://registry.npmjs.org/@angular%2fplatform-browser-dynamic failed, reason: getaddrinfo ENOTFOUND host host:80
57 silly fetchPackageMetaData error for @angular/router@^4.0.0 request to https://registry.npmjs.org/@angular%2frouter failed, reason: getaddrinfo ENOTFOUND host host:80
58 silly fetchPackageMetaData error for bootstrap@^3.3.7 request to https://registry.npmjs.org/bootstrap failed, reason: getaddrinfo ENOTFOUND host host:80
59 silly fetchPackageMetaData error for rxjs@^5.4.1 request to https://registry.npmjs.org/rxjs failed, reason: getaddrinfo ENOTFOUND host host:80
60 silly fetchPackageMetaData error for core-js@^2.4.1 request to https://registry.npmjs.org/core-js failed, reason: getaddrinfo ENOTFOUND host host:80
61 silly fetchPackageMetaData error for zone.js@^0.8.14 request to https://registry.npmjs.org/zone.js failed, reason: getaddrinfo ENOTFOUND host host:80
62 timing stage:rollbackFailedOptional Completed in 1ms
63 timing stage:runTopLevelLifecycles Completed in 27870ms
64 silly saveTree apm@0.0.0
65 verbose type system
66 verbose stack FetchError: request to https://registry.npmjs.org/@angular%2fcommon failed, reason: getaddrinfo ENOTFOUND host host:80
66 verbose stack     at ClientRequest.req.on.err (C:\Users\ishaq\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
66 verbose stack     at emitOne (events.js:116:13)
66 verbose stack     at ClientRequest.emit (events.js:211:7)
66 verbose stack     at onerror (C:\Users\ishaq\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:100:9)
66 verbose stack     at callbackError (C:\Users\ishaq\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:122:5)
66 verbose stack     at <anonymous>
66 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
67 verbose cwd C:\Users\ishaq\OneDrive\nationalExpress\Angular-GettingStarted-master\Angular-GettingStarted-master\APM-Start
68 verbose Windows_NT 10.0.14393
69 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ishaq\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
70 verbose node v8.11.3
71 verbose npm  v6.1.0
72 error code ENOTFOUND
73 error errno ENOTFOUND
74 error network request to https://registry.npmjs.org/@angular%2fcommon failed, reason: getaddrinfo ENOTFOUND host host:80
75 error network This is a problem related to network connectivity.
75 error network In most cases you are behind a proxy or have bad network settings.
75 error network
75 error network If you are behind a proxy, please make sure that the
75 error network 'proxy' config is set properly.  See: 'npm help config'
76 verbose exit [ 1, true ]

**Comment by DeborahK** [comment]
The error message specifically states:

75 error network This is a problem related to network connectivity.
75 error network In most cases you are behind a proxy or have bad network settings.

If you are not able to install and run npm then you will not be able to build Angular application's locally. If you are at work, consider contacting your IT department to set up the proxy settings appropriately.

Alternatively, if you can access the web, try using stackblitz during the course by using this link:

https://stackblitz.com/github/DeborahK/Angular-GettingStarted/tree/master/APM-Start

This allows you to build and run Angular applications without downloading anything. So no need for npm.

Let me know if that helps.
