### ISSUE TITLE
Gulp-util deprecated

### ISSUE THREAD

**Issue by JurgenG** [DeborahK/Angular-GettingStarted#95]
Gulp-util is deprecated and should be removed. I think it would be a smart thing to update your code accordingly...
https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by DeborahK** [comment]
Thank you for your suggestion.

My code does not use `gulp-util`. If it is being pulled in with `npm install` ... then a package that Angular uses is pulling it in and I can't just remove it.

Consider posting your suggestion to the Angular repo.

Thanks again.
