### ISSUE TITLE
Anuglar Getting Started  Course- Issue

### ISSUE THREAD

**Issue by shaheenaakhter** [DeborahK/Angular-GettingStarted#97]
Hi Deborah,

I'm doing Angular Getting Started Course from plural sight.I'm using the sample code given in the course.I'm stuck at displaying product details component.The code I have used is as below.This code is from product.service.ts.

  getProducts(): Observable<IProduct[]> {
        return this._http.get<IProduct[]>(this._productUrl).pipe(
          tap(data => console.log('All: ' + JSON.stringify(data))),
          catchError(this.handleError), );
      }

Trying to debug the code,the error says IProduct[] is not defined.
Could you please help me to solve the issue.I'm stuck with this please.

Thanks for your help in Advance.

Thanks,
Shaheena

![image](https://user-images.githubusercontent.com/40046371/43240545-30585bba-90eb-11e8-870a-50984a7255b0.png)

**Comment by DeborahK** [comment]
Hi! It would be great if you could post questions about the course in the Pluralsight discussion group for the course. You can find that here: [Angular: Getting Started Discussion](https://app.pluralsight.com/library/courses/angular-2-getting-started-update/discussion)

A few things to check:
- Do you have the interface defined (in product.ts)?
- Do you have the import statement for the interface defined in the service?
- You have an extra comma at the end (though I doubt that would cause this error).

Let me know if these suggestions don't resolve your issue and I'll look into it further.

**Comment by shaheenaakhter** [comment]
Angular Getting started -Issue :Product-detail page is empty.

Hi Deborah,

Thanks for the email.I have defined the 
1.interface in product.ts
2.have used  - import { IProduct } from "./product"; in product.service.ts
3.These is the code block from product.service.ts
@Injectable()
export class ProductService{
    private productUrl = "api/products/products.json";
    
    constructor(private _http:HttpClient){}

   getProducts(): Observable<IProduct[]> {
        return this._http.get<IProduct[]>(this.productUrl).pipe(
          tap(data => console.log('All: ' + JSON.stringify(data)),
          catchError(this.handleError)));
      }

    getProduct(id: number): Observable<IProduct> {
        return this.getProducts().pipe(
            map((products: IProduct[]) => products.find(p => p.productID === id)));
      }
 private handleError(err:HttpErrorResponse)
    {
        console.log(err.message);
        return Observable.throw(err.message);
}
    
4.Thie below is from product-detail.component.ts

import { Component, OnInit } from '@angular/core';
import { IProduct } from './product';
import { ActivatedRoute } from '@angular/router';
import { Router} from '@angular/router';
import { ProductService } from './product.service';
@Component({
  templateUrl: './product-detail.component.html',
  styleUrls: ['./product-detail.component.css']
})

export class ProductDetailComponent implements OnInit {
   pageTitle:string ='Product Detail';
   errorMessage:string;
   product:IProduct;
  constructor(private _route:ActivatedRoute,
              private _router:Router,
              private _productService:ProductService) { }

  ngOnInit() {
    const param = +this._route.snapshot.paramMap.get('id');
    this.pageTitle += `: ${param}`;
    if (param)
    {
      const id = + param;
      this.getProduct(id);
    }

 getProduct(id: number) {
      this._productService.getProduct(id).subscribe(
        product => this.product = product,
        error => this.errorMessage = <any>error);
      }

onBack():void {
  this._router.navigate(['/products']);
}

Trying to log the issue on plural sight discussion group,but looks like the page is down.

Thanks,
Shaheena

**Comment by DeborahK** [comment]
I replied on the Pluralsight page. So I'm closing this issue here.

Hope we'll be able to resolve your issue. Note that I'm out of the office tomorrow and for the week-end.
