### ISSUE TITLE
npm start does not run after I ran update to node(8.11.3) and npm version(6.2.0)

### ISSUE THREAD

**Issue by fluxquantum** [DeborahK/Angular-GettingStarted#98]
I'm seeing the following error when I run npm start.

ERROR in C:/Users/bcheng94/Documents/Angular-Getting-Started-Deborah/APM-Start/src/main.ts
Module build failed: Error: C:\Users\bcheng94\Documents\Angular-Getting-Started-Deborah\APM-Start\src\main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\bcheng94\Documents\Angular-Getting-Started-Deborah\APM-Start\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
    at plugin.done.then (C:\Users\bcheng94\Documents\Angular-Getting-Started-Deborah\APM-Start\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>
ERROR in C:/Users/bcheng94/Documents/Angular-Getting-Started-Deborah/APM-Start/src/polyfills.ts
Module build failed: Error: C:\Users\bcheng94\Documents\Angular-Getting-Started-Deborah\APM-Start\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\bcheng94\Documents\Angular-Getting-Started-Deborah\APM-Start\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
    at plugin.done.then (C:\Users\bcheng94\Documents\Angular-Getting-Started-Deborah\APM-Start\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>

I deleted my node modules and reran npm install and still got the same error. I'm trying to run things from the apm-start folder.

**Comment by DeborahK** [comment]
Any chance you don't have the latest files from my github? This course was updated a few weeks ago. Could you try deleting the entire folder and download the code from this github again?

Then ensure you are in the APM-Start folder and run `npm install`. Let me know if you see any errors at that point.

**Comment by fluxquantum** [comment]
I definitely have a fresh check out of the code. I only started this course a few days ago. I ran into this problem in the apm-start folder and even ran in a separate apm folder based (if for some reason the path was an issue somewhere) on the walkthrough video but I still see the same problem.

I even bumped my node and npm version to match the one indicated in your walk through.

**Comment by DeborahK** [comment]
Hmmm . I've had literally 100's of downloads of this repo and have not seen this error before. I retried it earlier today and it worked fine for me.

Can you think of anything else that may be different in your setup? Any chance you have an older version of tsc (the Typescript compiler) on your environment path?

Have you installed the Angular cli? Does that work for you?

**Comment by fluxquantum** [comment]
So, you are suggesting that I try to setup the project using the angular cli instead of just using the APM-start files that I checked out? How do I check my typescript compiler? That was not something that I configured explicitly anywhere.

Thank you for your time.

**Comment by DeborahK** [comment]
I was suggesting just trying the cli to see if you can run 'npm start' with the resulting code. That would tell us if this is a general issue or one specific to only my repo.

**Comment by DeborahK** [comment]
What os are you using?

**Comment by fluxquantum** [comment]
Hi Deborah, I am using windows 8. And yes, in cygwin I did use npm start to try to run the app.

**Comment by DeborahK** [comment]
Did using the CLI work?

To check your path to see if tsc is included on that path, follow the instructions here: https://www.computerhope.com/issues/ch000549.htm

**Comment by fluxquantum** [comment]
I do not see tsc in my environment variables. Where am I suppose to look for that?

**Comment by DeborahK** [comment]
![image](https://user-images.githubusercontent.com/7987365/43607660-b1dc1d6c-9653-11e8-943a-7068fc8a727f.png)

**Comment by DeborahK** [comment]
In the Environment Variables dialog on the right I picked `Path` and then `Edit`, which brought up the dialog on the left.

There should be *no* path to tsc listed. If there is, remove it.

**Comment by DeborahK** [comment]
And if you want to give up on trying to install this ... you can use www.stackblitz instead. It allows you to work with the code online without having to install it locally.

**Comment by DeborahK** [comment]
Yes.

**Comment by fluxquantum** [comment]
I have the following in my path already: C:\Program Files (x86)\Microsoft VS Code\bin;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\bcheng94\AppData\Roaming\npm

I'll try stackblitz for now. Not sure why my system is acting up. Thank you for your time.
